language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - ./gradlew build
  - ./gradlew jacocoTestReport
  - ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN

