language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - ./gradlew build
  - ./gradlew -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=mrfroop-github -Dsonar.login=$SONAR_TOKEN sonarqube
