language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build
  - ./gradle detekt
  - ./gradlew -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=mrfroop-github -Dsonar.login=$SONAR_TOKEN sonarqube
