version: '{branch} {build}'
branches:
  only:
  - master
skip_tags: true
clone_depth: 10
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
build_script:
- cmd: gradlew.bat assemble --no-daemon
test_script:
- cmd: gradlew.bat check jacocoTestReport jacocoTestCoverageVerification --no-daemon